name: Vulnerability Scan
on:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Clone SBOM Alert Generator
        run: |
          git clone https://github.com/mifugnius/SBOMAlertGenerator.git
  
      - name: Install dependencies
        run: |
          cd SBOMAlertGenerator
          pip install -r requirements.txt
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Run vulnerability scan on PR branch
        run: |
            echo "Running scheduled Alert Generator"
            python SBOMAlertGenerator/main.py --directory-to-scan=. --smtp-server-name=${{ secrets.SMTP_SERVER_NAME }} --smtp-port=${{ secrets.SMTP_PORT }} --smtp-username=${{ secrets.SMTP_USERNAME }} --smtp-password=${{ secrets.SMTP_MASTER_PASSWORD }} --email-from=${{ secrets.EMAIL_FROM }}
